export const USER_MESSAGES = {
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  REGISTER: 'REGISTER',
  AC_VERIFICATION_TOKEN: 'AC_VERIFICATION_TOKEN',
  GENERATE_TOKEN: 'GENERATE_TOKEN',
  GENERATE_PASSWORD_RESET_TOKEN: 'GENERATE_PASSWORD_RESET_TOKEN',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
};
